// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package generated

type FooBar struct {
	V int `json:"v"`
}

type Object struct {
	FooBar *FooBar `json:"foo_bar,omitempty"`
	FooBar *FooBar `json:"fooBar,omitempty"`
}

type Query struct {
}
